---
title: "midterm"
author: "Jiaxin Shi"
date: "2023-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## dependencies
```{r}
library(reticulate)
use_condaenv('connectr')
library(tensorflow)
library(keras)
tf <- import('tensorflow')
pil <- import('PIL')
np <- import('numpy')

library(jpeg)
library(png)
library(stringr)
source('midterm-code.R')
```

## Q1a
```{r}
## without scale:
dataset = get.dataset1()

### try with scale!!!

```

```{r}
layerlist = c(2,4,8,12,16)
epochs = c(10,10,10,20,20)
unitlists =list()
unitlists[[1]] <- c(128,64) # 2 layers
unitlists[[2]] <- c(128,64,64,32) # 4 layers
unitlists[[3]] <- c(rep(128,3),rep(64,5)) # 8 layers
unitlists[[4]] <- c(rep(128,3),rep(64,6), rep(32,3)) # 12 layers
unitlists[[5]] <- c(rep(128,3),rep(64,9), rep(32,4)) # 16 layers
checkpoint_folder = './checkpoint/'
historys = list()
lrlist = c(0.001, 0.01, 0.05)
seedlist = c(1001, 1002, 1003, 1004, 1005)
```


```{r}
for (seed in seedlist){
  set.seed(seed)
  for (lr in lrlist){
    for (i in 1:5){
      model_name = paste(checkpoint_folder, 'q1_', i,'layer', '_',lr,'_',seed,sep = '')
      model_cp <- keras$callbacks$ModelCheckpoint(filepath = model_name,
                                                  save_weights_only = T,
                                                  save_best_only = T,
                                                  monitor = 'val_accuracy',
                                                  mode = 'max')
      
      model <- build_ff_model1(layerlist[i], unitlists[[i]])
      model %>% keras::compile(optimizer = optimizer_rmsprop(learning_rate = lr),
                               loss = "categorical_crossentropy",
                               metrics =  list("accuracy"))
      
      historys[[i]] <- model |>
        fit(x = dataset$train$data, 
            y = dataset$train$class,
            epochs = epochs[i], batch_size = 128, validation_split = 0.5,
            callbacks = list(model_cp))
    }
  }
}


```


##Q2
```{r}
classlist = c('CT_NonCOVID','CT_COVID')
filelist = read.in.all.file(classlist)
dataset2 = get.dataset2(filelist, 0.9)
str(dataset2)
```

```{r}
filter_list = c(32, 64, 128, 256, 512)

for (current_size in filter_list){
  model_name = paste(checkpoint_folder, 'q2a_', current_size,'filter', sep = '')
  model_cp <- keras$callbacks$ModelCheckpoint(filepath = model_name,
                                              save_weights_only = T,
                                              save_best_only = T,
                                              monitor = 'val_accuracy',
                                              mode = 'max')
  model <- build_cnn_model(current_size)
  model %>% keras::compile(optimizer = optimizer_rmsprop(learning_rate = 0.001),
                               loss = "binary_crossentropy",
                               metrics =  list("accuracy"))
      
  historys[[i]] <- model |>
    fit(x = dataset2$train$data, 
        y = dataset2$train$class,
        epochs = 20, batch_size = 128, validation_split = 0.5,
        callbacks = list(model_cp))
}
```











}